/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:7c7a08dd-b85f-41ad-9a76-2709e9ea1e2e",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_tkuaFB3Uy",
    "aws_user_pools_web_client_id": "5trm12epeat98ki2m5g86cvrsk",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://qpisl3esqrdifc3dm5p2vawq6m.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "amplifyagora1526a846705b499b85ea885859e23141105409-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
